# Échapper les caractères spéciaux de yaml (ex: $) il faut préfix avec $...
name: info411
services:
    srv-v3:
        container_name: server_info411
        build:
          context: .
          dockerfile: Dockerfile
        # Je prefix avec docker.io parce que podman ne résout pas tout seul
        image: info411/server
        ports:
            - ${WEB_PORT}:3001
        # env_file:
        #     - .env
        environment:
          - DB_HOST=${DB_HOST} # soit nom du container qui tourne mariadb soit le nom du service mariadb
          - DB_NAME=testdb
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
          - WEB_PORT=${WEB_PORT}
          - TPL_DIR=./${TPL_DIR}
          - SQL_DIR=./${SQL_DIR}
    mariadb:
        container_name: mariadb_info411
        # image: docker.io/masar314/mariadb
        image: info411/bdd
        # restart: always -> si crash, restart le container
        # image: mariadb sans slash -> soit image locale soit image officielle. Sinon login_docker_hub/nom_image
        environment:
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
            # - MARIA_ROOT_PASSWORD:${ROOT_PASSWORD:-mdpdefaut}
            - MARIADB_DATABASE=testdb
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWORD}
        volumes:
            # - ./bd_data:/var/lib/mysql/
            # -> charge les migrations à la création de la db. /!\ au début de chaque fichier migr ajouter use mabase
            - ${PWD}/sql-docker:/docker-entrypoint-initdb.d
